# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build Test Release

on:
  release:
    types: [ published, created, edited ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: change pr
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Build test report
        run: ./gradlew test jacocoTestReport

      - name: Show tree
        run: sudo apt-get install tree | tree
      - shell: bash
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        run: |
          bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r build/reports/jacoco/test/jacocoTestReport.xml

      - name: Get latest release version number
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Publish art
        env:
          USER_NAME: ${{ secrets.USER_NAME }}
          TOKEN: ${{ secrets.TOKEN }}
          GET_VERSION: ${{ steps.get_version.outputs.version }}
        run: ./gradlew build publish


